-- Sample Data for Pizza Mamma Mia
-- Realistic test data for the database

--DISCLAIMER: This was generated by LLM

-- =============================================
-- INGREDIENTS
-- =============================================
INSERT INTO Ingredient (name, cost, is_meat, is_animal_prod) VALUES
-- Base ingredients
('Tomato Sauce', 0.50, FALSE, FALSE),
('Mozzarella Cheese', 1.20, FALSE, TRUE),
('Olive Oil', 0.30, FALSE, FALSE),
('Dough', 0.40, FALSE, FALSE),

-- Vegetables
('Mushrooms', 0.80, FALSE, FALSE),
('Bell Peppers', 0.60, FALSE, FALSE),
('Onions', 0.40, FALSE, FALSE),
('Tomatoes', 0.50, FALSE, FALSE),
('Olives', 0.70, FALSE, FALSE),
('Spinach', 0.60, FALSE, FALSE),
('Arugula', 0.70, FALSE, FALSE),
('Basil', 0.40, FALSE, FALSE),
('Garlic', 0.30, FALSE, FALSE),
('Jalapeños', 0.60, FALSE, FALSE),
('Pineapple', 0.80, FALSE, FALSE),

-- Meats
('Pepperoni', 1.50, TRUE, TRUE),
('Italian Sausage', 1.40, TRUE, TRUE),
('Ham', 1.30, TRUE, TRUE),
('Bacon', 1.60, TRUE, TRUE),
('Chicken', 1.80, TRUE, TRUE),
('Beef', 2.00, TRUE, TRUE),
('Anchovies', 1.90, TRUE, TRUE),

-- Cheese varieties
('Parmesan', 1.50, FALSE, TRUE),
('Gorgonzola', 1.70, FALSE, TRUE),
('Ricotta', 1.30, FALSE, TRUE),
('Feta', 1.40, FALSE, TRUE);

-- =============================================
-- PIZZAS (10 pizzas)
-- =============================================
INSERT INTO Pizza (name, price, is_vegetarian, is_vegan, active) VALUES
('Margherita', 8.99, TRUE, FALSE, TRUE),
('Pepperoni Classic', 10.99, FALSE, FALSE, TRUE),
('Vegetarian Supreme', 11.99, TRUE, FALSE, TRUE),
('Hawaiian', 10.99, FALSE, FALSE, TRUE),
('BBQ Chicken', 12.99, FALSE, FALSE, TRUE),
('Meat Lovers', 13.99, FALSE, FALSE, TRUE),
('Four Cheese', 11.99, TRUE, FALSE, TRUE),
('Mediterranean', 11.99, TRUE, FALSE, TRUE),
('Spicy Diavola', 11.99, FALSE, FALSE, TRUE),
('Mushroom Truffle', 12.99, TRUE, FALSE, TRUE);

-- =============================================
-- PIZZA-INGREDIENT RELATIONSHIPS
-- =============================================

-- Margherita (pizza_id: 1)
INSERT INTO PizzaIngredient (pizza_id, ingredient_id, grams) VALUES
(1, 1, 100),  -- Tomato Sauce
(1, 2, 150),  -- Mozzarella
(1, 3, 10),   -- Olive Oil
(1, 4, 250),  -- Dough
(1, 12, 5);   -- Basil

-- Pepperoni Classic (pizza_id: 2)
INSERT INTO PizzaIngredient (pizza_id, ingredient_id, grams) VALUES
(2, 1, 100),  -- Tomato Sauce
(2, 2, 150),  -- Mozzarella
(2, 4, 250),  -- Dough
(2, 16, 80);  -- Pepperoni

-- Vegetarian Supreme (pizza_id: 3)
INSERT INTO PizzaIngredient (pizza_id, ingredient_id, grams) VALUES
(3, 1, 100),  -- Tomato Sauce
(3, 2, 150),  -- Mozzarella
(3, 4, 250),  -- Dough
(3, 5, 60),   -- Mushrooms
(3, 6, 50),   -- Bell Peppers
(3, 7, 40),   -- Onions
(3, 8, 50),   -- Tomatoes
(3, 9, 30);   -- Olives

-- Hawaiian (pizza_id: 4)
INSERT INTO PizzaIngredient (pizza_id, ingredient_id, grams) VALUES
(4, 1, 100),  -- Tomato Sauce
(4, 2, 150),  -- Mozzarella
(4, 4, 250),  -- Dough
(4, 18, 70),  -- Ham
(4, 15, 80);  -- Pineapple

-- BBQ Chicken (pizza_id: 5)
INSERT INTO PizzaIngredient (pizza_id, ingredient_id, grams) VALUES
(5, 2, 150),  -- Mozzarella
(5, 4, 250),  -- Dough
(5, 20, 100), -- Chicken
(5, 7, 40),   -- Onions
(5, 6, 40);   -- Bell Peppers

-- Meat Lovers (pizza_id: 6)
INSERT INTO PizzaIngredient (pizza_id, ingredient_id, grams) VALUES
(6, 1, 100),  -- Tomato Sauce
(6, 2, 150),  -- Mozzarella
(6, 4, 250),  -- Dough
(6, 16, 60),  -- Pepperoni
(6, 17, 60),  -- Italian Sausage
(6, 19, 60),  -- Bacon
(6, 21, 60);  -- Beef

-- Four Cheese (pizza_id: 7)
INSERT INTO PizzaIngredient (pizza_id, ingredient_id, grams) VALUES
(7, 1, 80),   -- Tomato Sauce
(7, 2, 100),  -- Mozzarella
(7, 4, 250),  -- Dough
(7, 23, 50),  -- Parmesan
(7, 24, 50),  -- Gorgonzola
(7, 25, 50);  -- Ricotta

-- Mediterranean (pizza_id: 8)
INSERT INTO PizzaIngredient (pizza_id, ingredient_id, grams) VALUES
(8, 1, 100),  -- Tomato Sauce
(8, 2, 120),  -- Mozzarella
(8, 4, 250),  -- Dough
(8, 9, 40),   -- Olives
(8, 26, 50),  -- Feta
(8, 8, 50),   -- Tomatoes
(8, 11, 30),  -- Arugula
(8, 22, 40);  -- Anchovies

-- Spicy Diavola (pizza_id: 9)
INSERT INTO PizzaIngredient (pizza_id, ingredient_id, grams) VALUES
(9, 1, 100),  -- Tomato Sauce
(9, 2, 150),  -- Mozzarella
(9, 4, 250),  -- Dough
(9, 16, 80),  -- Pepperoni
(9, 14, 50),  -- Jalapeños
(9, 13, 10);  -- Garlic

-- Mushroom Truffle (pizza_id: 10)
INSERT INTO PizzaIngredient (pizza_id, ingredient_id, grams) VALUES
(10, 2, 150), -- Mozzarella
(10, 4, 250), -- Dough
(10, 5, 120), -- Mushrooms
(10, 3, 15),  -- Olive Oil
(10, 23, 40), -- Parmesan
(10, 13, 10); -- Garlic

-- =============================================
-- CUSTOMERS (10 customers with different ages and postcodes)
-- =============================================
--just some basic place holder passwords for now
INSERT INTO Customer (first_name, last_name, email, password, birth_date, postcode) VALUES
('John', 'Smith', 'john.smith@example.com', 'Password1!', '1990-05-15', '10001'),
('Emma', 'Johnson', 'emma.johnson@example.com', 'Password2!', '1985-08-22', '10002'),
('Michael', 'Williams', 'michael.williams@example.com', 'Password3!', '1978-03-10', '10003'),
('Sarah', 'Brown', 'sarah.brown@example.com', 'Password4!', '1995-11-30', '10001'),
('David', 'Jones', 'david.jones@example.com', 'Password5!', '1982-07-18', '10004'),
('Lisa', 'Garcia', 'lisa.garcia@example.com', 'Password6!', '1988-12-05', '10002'),
('Robert', 'Martinez', 'robert.martinez@example.com', 'Password7!', '1975-09-25', '10005'),
('Jennifer', 'Rodriguez', 'jennifer.rodriguez@example.com', 'Password8!', '1992-04-14', '10003'),
('William', 'Davis', 'william.davis@example.com', 'Password9!', '1980-06-20', '10001'),
('Maria', 'Lopez', 'maria.lopez@example.com', 'Password10!', '1998-01-08', '10004');

-- =============================================
-- DELIVERY PERSONNEL (3 delivery people)
-- =============================================
INSERT INTO DeliveryPerson (full_name, phone) VALUES
('Tony Soprano', '+1-555-0101'),
('Maria Rossi', '+1-555-0102'),
('Luigi Ferrari', '+1-555-0103');

-- =============================================
-- DISCOUNT CODES
-- =============================================
INSERT INTO DiscountCode (code, description, percent_off, amount_off, single_use) VALUES
('WELCOME10', 'Welcome discount for new customers', 10.00, NULL, TRUE),
('SAVE5', 'Save $5 on your order', NULL, 5.00, TRUE),
('LOYAL15', 'Loyalty reward - 15% off', 15.00, NULL, FALSE),
('BDAY2024', 'Birthday special discount', 20.00, NULL, TRUE),
('FREEPIZZA', 'Free pizza voucher', NULL, 10.00, TRUE);


-- ONSEN Coffee Collection (inspired by tom)
INSERT INTO Product (name, category, cost, is_alcohol) VALUES
-- ONSEN Specialty Coffees
('ONSEN Colombia Catura Chiroso', 'drink', 4.50, FALSE),
('ONSEN Costa Rica Villa Sarchi Tono', 'drink', 4.20, FALSE),
('ONSEN Ethiopia Guji Megadu', 'drink', 4.80, FALSE),
('ONSEN Guatamala El Naranjo', 'drink', 4.30, FALSE),
('Espresso', 'drink', 2.50, FALSE),
('Cappuccino', 'drink', 3.20, FALSE),
('Latte', 'drink', 3.50, FALSE),
('Americano', 'drink', 2.80, FALSE),

-- Soft Drinks
('Coca-Cola 330ml', 'drink', 1.20, FALSE),
('Sprite 330ml', 'drink', 1.20, FALSE),
('Fanta Orange 330ml', 'drink', 1.20, FALSE),
('Still Water 500ml', 'drink', 0.80, FALSE),
('Sparkling Water 500ml', 'drink', 1.00, FALSE),
('Orange Juice 250ml', 'drink', 2.00, FALSE),
('Apple Juice 250ml', 'drink', 2.00, FALSE),
('Iced Tea Lemon 330ml', 'drink', 1.50, FALSE),

-- Beers
('Heineken 330ml', 'drink', 2.50, TRUE),
('Corona Extra 355ml', 'drink', 2.80, TRUE),
('Peroni 330ml', 'drink', 2.70, TRUE),
('Craft IPA 500ml', 'drink', 3.50, TRUE),
('Belgian Wheat Beer 330ml', 'drink', 3.20, TRUE),

-- Snacks
('Garlic Bread (6 pieces)', 'snack', 2.50, FALSE),
('Bruschetta (4 pieces)', 'snack', 3.20, FALSE),
('Mozzarella Sticks (6 pieces)', 'snack', 3.50, FALSE),
('Chicken Wings (8 pieces)', 'snack', 4.50, FALSE),
('Caesar Salad', 'snack', 4.20, FALSE),
('Tiramisu (slice)', 'snack', 3.80, FALSE),
('Chocolate Brownie', 'snack', 3.20, FALSE),
('Panna Cotta', 'snack', 3.50, FALSE),
('Gelato (2 scoops)', 'snack', 3.00, FALSE),
('Cheesecake (slice)', 'snack', 4.00, FALSE);
