-- Sample Data for Pizza Mamma Mia
-- TODO: Insert realistic test data

-- TODO: Insert ingredients
-- INSERT INTO ingredients ...

-- TODO: Insert pizzas  
-- INSERT INTO pizzas ...

-- TODO: Insert pizza-ingredient relationships
-- INSERT INTO pizza_ingredients ...

-- TODO: Insert drinks and desserts
-- INSERT INTO drinks ...
-- INSERT INTO desserts ...

-- TODO: Insert customers (20+ with different ages, postcodes)
-- INSERT INTO customers ...

-- TODO: Insert delivery personnel
-- INSERT INTO delivery_personnel ...

-- TODO: Insert discount codes
-- INSERT INTO discount_codes ...

-- TODO: Insert sample orders (20+ across timeframes)
-- INSERT INTO orders ...
-- INSERT INTO order_items ...