-- Pizza Mamma Mia Database Schema
-- TODO: Create all tables with constraints

-- TODO: Customers table
-- CREATE TABLE customers (...

-- TODO: Ingredients table  
-- CREATE TABLE ingredients (...

-- TODO: Pizzas table (NO price column)
-- CREATE TABLE pizzas (...

-- TODO: Drinks table
-- CREATE TABLE drinks (...

-- TODO: Desserts table
-- CREATE TABLE desserts (...

-- TODO: Delivery personnel table
-- CREATE TABLE delivery_personnel (...

-- TODO: Discount codes table
-- CREATE TABLE discount_codes (...

-- TODO: Pizza-Ingredients junction table
-- CREATE TABLE pizza_ingredients (...

-- TODO: Orders table
-- CREATE TABLE orders (...

-- TODO: Order items table
-- CREATE TABLE order_items (...